import { useUser } from "@clerk/nextjs";
import { Household } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import { api } from "~/utils/api";

const HouseholdView: NextPage = () => {

  const router = useRouter();

  const transactions = api.transactions.getTransactionByHousehold.useQuery({id: router.query.id as string}, {enabled: !!router.query.id});


  return (
    <>
      <Head>
        <title>View Household Expenses</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center bg-gray-800 pt-24">
        <h1 className="text-4xl pb-12">Household Expenses</h1>
        <Link href={`/households/${router.query.id}/create-transaction`} className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Add New Expense
        </Link>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
       
        </div>
      </main>
    </>
  );
};

export default HouseholdView;
