import { useUser } from "@clerk/nextjs";
import { Household } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import { Modal } from "~/components/Modal";

import { api } from "~/utils/api";

type TransactionRowData = {
    id: string;
    payerName: string;
    name: string;
    amount: number;
    description: string;
}

type deleteData = {
    transactionId: string;
}

const HouseholdView: NextPage = () => {

  const [showModal, setShowModal] = useState(false);

  const [data, setData] = useState({
    transactionId: ''
  })

  const router = useRouter();

  const transactions = api.transactions.getTransactionByHousehold.useQuery({id: router.query.id as string}, {enabled: !!router.query.id});

  const deleteTransaction = api.transactions.deleteTransaction.useMutation();

  const id = String(router.query.id || '');


  const handleConfirm = () => {
    deleteTransaction.mutate(data);
    transactions.refetch().catch(err => {
        console.error(err);
    });
  }

  const openModal = (rowData: TransactionRowData) => {
    setData({transactionId: rowData.id});
    setShowModal(true);
  };

  return (
    <>
      <Head>
        <title>View Household Expenses</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex  min-h-screen flex-col items-center bg-gray-800 pt-24">
        <h1 className="text-4xl pb-12">Household Expenses</h1>
        <span className="pb-12">code: {router.query.id}</span>
        <Link href={`/households/${id}/create-transaction`} className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Add New Expense
        </Link>
        <div className="flex justify-center overflow-x-auto gap-12 px-4 py-16 w-full">

            
            <div className="relative w-full">
                <table className="w-full text-sm text-left text-gray-400">
                    <thead className="text-xs uppercase bg-gray-700 text-gray-400">
                        <tr>
                            <th scope="col" className="px-6 py-3">
                                Transaction Date
                            </th>
                            <th scope="col" className="px-6 py-3">
                                Spender
                            </th>
                            <th scope="col" className="px-6 py-3">
                                Name
                            </th>
                            <th scope="col" className="px-6 py-3">
                                Amount
                            </th>
                            <th scope="col" className="px-6 py-3">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        {transactions?.data?.map((transaction) =>
                            <tr key={transaction.id} className="border-b bg-gray-800 border-gray-700">
                                <th scope="row" className="px-6 py-4 font-medium whitespace-nowrap text-white">
                                    {transaction.createdAt.toDateString()}
                                </th>
                                <td className="px-6 py-4">
                                    {transaction.payerName}
                                </td>
                                <td className="px-6 py-4">
                                    {transaction.name}
                                </td>
                                <td className="px-6 py-4">
                                    {transaction.amount}
                                </td>
                                <td className="px-6 py-4">
                                    <button onClick={() => { openModal(transaction); }} className="font-medium text-red-500 hover:underline">Remove</button>
                                </td>
                            </tr>
                        )}
                        
                    </tbody>
                </table>
            </div>
        </div>

        <Modal show={showModal} setShowModal={setShowModal} handleConfirm={handleConfirm}/>
      </main>
    </>
  );
};

export default HouseholdView;
