import { useUser } from "@clerk/nextjs";
import { type Household } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

function Card({household}: {household: Household}) {
  return (
    
    <div className="max-w-sm h-30 w-60 p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        
        <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{household.name}</h5>
        
        {/* <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p> */}
        <Link href={`/households/${household.id}`} className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            View
            <svg aria-hidden="true" className="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
        </Link>
    </div>

  )
}

const Home: NextPage = () => {

  const user = useUser();

  const households = api.households.getHouseholdsByUser.useQuery();

  console.log(user)

  return (
    <>
      <Head>
        <title>Households</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center bg-gray-800">

        <h1 className="text-4xl pb-12 pt-16">Households</h1>

        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {households?.data?.map((household) =>
            <Card key={household.id} household={household}/>
          )}
        </div>

        <Link href="/join-household" className=" text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
            Join a household
        </Link>
      </main>
    </>
  );
};

export default Home;
